### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by parenyukln** [Cap-Coding/symfony_docker#3]
After just clone your repo and docker-compose up -d command execution I have 502 Bad Gateway Nginx error on route localhost:8080/api/v1/orders/1

Logs: 
2021/01/13 12:43:45 [error] 30#30: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: , request: "GET /api/v1/orders/1 HTTP/1.1", upstream: "fastcgi://172.20.0.3:9001", host: "localhost:8080"

**Comment by kurakin-oleksandr** [comment]
Hi @parenyukln 
Thank you for reporting this issue. I can confirm that it does not work now. I'll provide fix soon

**Comment by parenyukln** [comment]
> Hi @parenyukln
> Thank you for reporting this issue. I can confirm that it does not work now. I'll provide fix soon

**Comment by parenyukln** [comment]
Thanx, I'll be waiting for it :)

**Comment by kurakin-oleksandr** [comment]
Please check, should be fixed now

`make rebuild`
`make db`
